const MagData = [
  {
    id: 1,
    slug: "Mag_1",
    title: "The Renaissance of Rouge",
    info: "The Renaissance of Rouge",
    Words_By: "Eleanor Vance",
    Published: "April 12, 2024",
    Read_Time: "8 min read",
    img: "/images/mag1.png",
    para_1:
      "There is something undeniably powerful about a red lip. It is not merely a cosmetic choice; it is a declaration.",
    para_heading_1: "A History of Power",
    para_2:
      "From Cleopatra to Hollywood icons, red lipstick has always carried cultural weight.",
    title_2: "Give a woman the right lipstick and she can conquer the world",
    para_heading_2: "The Modern Application",
    para_3:
      "Today’s red is versatile and wearable, from casual brunch to corporate boardrooms.",
    para_heading_3: "Finding Your Shade",
    para_4: "The perfect red depends on undertone and confidence.",
    arthur: "Eleanor Vance",
    job: "Beauty Editor",
  },

  {
    id: 2,
    slug: "Mag_2",
    title: "Minimalism Reimagined",
    info: "Minimalism Reimagined",
    Words_By: "Clara Bennett",
    Published: "May 3, 2024",
    Read_Time: "6 min read",
    img: "/images/mag2.png",
    para_1:
      "Minimalism in 2024 is no longer about emptiness but intentional curation.",
    para_heading_1: "Less But Better",
    para_2: "The focus has shifted from decluttering to mindful ownership.",
    title_2: "Luxury is space, not stuff",
    para_heading_2: "Design Evolution",
    para_3: "Neutral palettes now include texture and organic materials.",
    para_heading_3: "Living the Philosophy",
    para_4: "Minimalism is a mindset that values clarity over chaos.",
    arthur: "Clara Bennett",
    job: "Lifestyle Editor",
  },

  {
    id: 3,
    slug: "Mag_3",
    title: "The Art of Slow Fashion",
    info: "The Art of Slow Fashion",
    Words_By: "Maya Laurent",
    Published: "June 18, 2024",
    Read_Time: "7 min read",
    img: "/images/mag3.png",
    para_1: "Fast fashion is fading as consumers embrace sustainability.",
    para_heading_1: "Quality Over Quantity",
    para_2: "Timeless tailoring is replacing trend-driven wardrobes.",
    title_2: "Buy less. Choose well.",
    para_heading_2: "Ethical Craftsmanship",
    para_3: "Brands are investing in fair labor and eco fabrics.",
    para_heading_3: "Future of Style",
    para_4: "Slow fashion signals conscious consumerism.",
    arthur: "Maya Laurent",
    job: "Fashion Writer",
  },

  {
    id: 4,
    slug: "Mag_4",
    title: "Digital Detox Diaries",
    info: "Digital Detox Diaries",
    Words_By: "Oliver Hayes",
    Published: "July 9, 2024",
    Read_Time: "5 min read",
    img: "/images/mag_Info1.png",
    para_1: "Constant notifications are redefining attention spans.",
    para_heading_1: "Disconnect to Reconnect",
    para_2: "Reducing screen time improves creativity and sleep.",
    title_2: "Silence is the new luxury",
    para_heading_2: "Practical Steps",
    para_3: "Scheduled breaks and phone-free mornings are effective.",
    para_heading_3: "Mental Clarity",
    para_4: "Digital balance restores personal focus.",
    arthur: "Oliver Hayes",
    job: "Tech Columnist",
  },

  {
    id: 5,
    slug: "Mag_5",
    title: "Modern Skincare Rituals",
    info: "Modern Skincare Rituals",
    Words_By: "Isabella Moore",
    Published: "August 2, 2024",
    Read_Time: "9 min read",
    img: "/images/mag_Info2.png",
    para_1: "Skincare has evolved into a daily ritual of self-care.",
    para_heading_1: "Ingredient Intelligence",
    para_2: "Consumers now understand actives like retinol and niacinamide.",
    title_2: "Healthy skin is always in",
    para_heading_2: "Layering Techniques",
    para_3: "Correct sequencing enhances product performance.",
    para_heading_3: "Consistency is Key",
    para_4: "Results come from routine, not trends.",
    arthur: "Isabella Moore",
    job: "Beauty Specialist",
  },

  {
    id: 6,
    slug: "Mag_6",
    title: "The Rise of Home Cafés",
    info: "The Rise of Home Cafés",
    Words_By: "Daniel Brooks",
    Published: "September 14, 2024",
    Read_Time: "6 min read",
    img: "/images/mag4.png ",
    para_1: "Home coffee culture is redefining mornings.",
    para_heading_1: "Barista Basics",
    para_2: "Espresso machines are now household staples.",
    title_2: "Brewed to perfection",
    para_heading_2: "Aesthetic Corners",
    para_3: "Instagram-inspired setups elevate simple routines.",
    para_heading_3: "Beyond Coffee",
    para_4: "It’s about atmosphere and mindfulness.",
    arthur: "Daniel Brooks",
    job: "Culture Writer",
  },

  {
    id: 7,
    slug: "Mag_7",
    title: "Wellness Beyond Trends",
    info: "Wellness Beyond Trends",
    Words_By: "Sophia Clarke",
    Published: "October 5, 2024",
    Read_Time: "7 min read",
    img: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&q=80&w=800",
    para_1: "Wellness in 2024 is rooted in sustainability, not fads.",
    para_heading_1: "Holistic Health",
    para_2: "Mental, physical, and emotional health are interconnected.",
    title_2: "Balance is power",
    para_heading_2: "Daily Habits",
    para_3: "Small consistent actions outweigh extreme programs.",
    para_heading_3: "Long-Term Vision",
    para_4: "Wellness is a lifestyle commitment.",
    arthur: "Sophia Clarke",
    job: "Health Editor",
  },

  {
    id: 8,
    slug: "Mag_8",
    title: "Timeless Interior Design",
    info: "Timeless Interior Design",
    Words_By: "Lucas Martin",
    Published: "November 20, 2024",
    Read_Time: "8 min read",
    img: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&q=80&w=800",
    para_1: "Trends fade, but timeless design endures.",
    para_heading_1: "Foundation First",
    para_2: "Neutral bases allow seasonal updates.",
    title_2: "Elegance is longevity",
    para_heading_2: "Material Matters",
    para_3: "Natural wood, stone, and linen remain classics.",
    para_heading_3: "Design for Living",
    para_4: "Homes should reflect personality and comfort.",
    arthur: "Lucas Martin",
    job: "Interior Stylist",
  },
];
export default MagData;
