const Products = [
  // ---------------- LOTION ----------------
  {
    id: 1,
    category: "Lotion",
    img: "/images/Lotion1.png",
    RegularPrice: 1299,
    SalePrice: 1199,
    info: "Glow Skin Lotion",
  },
  {
    id: 2,
    category: "Lotion",
    img: "/images/Lotion2.png",
    RegularPrice: 1399,
    SalePrice: 1249,
    info: "Hydrating Aloe Lotion",
  },
  {
    id: 3,
    category: "Lotion",
    img: "/images/Lotion3.png",
    RegularPrice: 1499,
    SalePrice: 1349,
    info: "Daily Moisture Body Lotion",
  },
  {
    id: 4,
    category: "Lotion",
    img: "/images/Lotion4.png",
    RegularPrice: 1599,
    SalePrice: 1449,
    info: "Shea Butter Repair Lotion",
  },

  // ---------------- LIPSTICK ----------------
  {
    id: 5,
    category: "Lipstick",
    img: "/images/Lipstick1.jpg",
    RegularPrice: 1099,
    SalePrice: 899,
    info: "Matte Red Lipstick",
  },
  {
    id: 6,
    category: "Lipstick",
    img: "/images/Lipstick2.jpg",
    RegularPrice: 1199,
    SalePrice: 999,
    info: "Nude Velvet Lipstick",
  },
  {
    id: 7,
    category: "Lipstick",
    img: "/images/Lipstick3.jpg",
    RegularPrice: 1299,
    SalePrice: 1099,
    info: "Soft Pink Gloss Lipstick",
  },
  {
    id: 8,
    category: "Lipstick",
    img: "/images/Lipstick4.jpg",
    RegularPrice: 1399,
    SalePrice: 1199,
    info: "Long Lasting Plum",
  },

  // ---------------- MASCARA ----------------
  {
    id: 9,
    category: "Mascara",
    img: "/images/Mascara1.jpg",
    RegularPrice: 1199,
    SalePrice: 999,
    info: "Volume Boost Mascara",
  },
  {
    id: 10,
    category: "Mascara",
    img: "/images/Mascara2.jpg",
    RegularPrice: 1299,
    SalePrice: 1099,
    info: "Waterproof Curl Mascara",
  },
  {
    id: 11,
    category: "Mascara",
    img: "/images/Mascara3.jpg",
    RegularPrice: 1399,
    SalePrice: 1199,
    info: "Extra Length Mascara",
  },
  {
    id: 12,
    category: "Mascara",
    img: "/images/Mascara4.jpg",
    RegularPrice: 1499,
    SalePrice: 1299,
    info: "Deep Black Lash Mascara",
  },

  // ---------------- SERUM ----------------
  {
    id: 13,
    category: "Serum",
    img: "/images/Serum1.jpg",
    RegularPrice: 1799,
    SalePrice: 1499,
    info: "Vitamin C Serum",
  },
  {
    id: 14,
    category: "Serum",
    img: "/images/Serum2.png",
    RegularPrice: 1899,
    SalePrice: 1599,
    info: "Niacinamide Brightening Serum",
  },
  {
    id: 15,
    category: "Serum",
    img: "/images/Serum3.jpg",
    RegularPrice: 1999,
    SalePrice: 1699,
    info: "Anti Aging Retinol Serum",
  },
  {
    id: 16,
    category: "Serum",
    img: "/images/Serum4.png",
    RegularPrice: 2099,
    SalePrice: 1799,
    info: "Hyaluronic Hydration Serum",
  },

  // ---------------- CONCEALER ----------------
  {
    id: 17,
    category: "Concealer",
    img: "/images/Concealer1.jpg",
    RegularPrice: 999,
    SalePrice: 799,
    info: "Full Coverage Concealer",
  },
  {
    id: 18,
    category: "Concealer",
    img: "/images/Concealer2.jpg",
    RegularPrice: 1099,
    SalePrice: 899,
    info: "Matte Finish Concealer",
  },
  {
    id: 19,
    category: "Concealer",
    img: "/images/Concealer3.jpg",
    RegularPrice: 1199,
    SalePrice: 999,
    info: "Hydrating Liquid Concealer",
  },
  {
    id: 20,
    category: "Concealer",
    img: "/images/Concealer4.jpg",
    RegularPrice: 1299,
    SalePrice: 1099,
    info: "Spot Correct Concealer",
  },
];
export default Products;
