const ShopProducts = [
  {
    id: 1,
    img: "/Products/makeup/makeup1.png",
    price: 999,
    DiscountPrice: 899,
    info: "Matte Lipstick",
    category: "Make-up",
  },
  {
    id: 2,
    img: "/Products/makeup/makeup2.png",
    price: 1899,
    DiscountPrice: 1599,
    info: "Foundation",
    category: "Make-up",
  },
  {
    id: 3,
    img: "/Products/makeup/makeup3.png",
    price: 799,
    DiscountPrice: 499,
    info: "Liquid Eyeliner",
    category: "Make-up",
  },
  {
    id: 4,
    img: "/Products/makeup/makeup4.png",
    price: 1499,
    DiscountPrice: 1199,
    info: "Blush Palette",
    category: "Make-up",
  },
  {
    id: 5,
    img: "/Products/makeup/makeup1.png",
    price: 799,
    DiscountPrice: 999,
    info: "Mascara Volume",
    category: "Make-up",
  },
  {
    id: 6,
    img: "/Products/skincare/skincare1.png",
    price: 1299,
    DiscountPrice: 1199,
    info: "Glow Skin",
    category: "Skincare",
  },
  {
    id: 7,
    img: "/Products/skincare/skincare2.png",
    price: 1299,
    DiscountPrice: 1199,
    info: "Hydrating Serum",
    category: "Skincare",
  },
  {
    id: 8,
    img: "/Products/skincare/skincare3.png",
    price: 1199,
    DiscountPrice: 999,
    info: "Night Cream",
    category: "Skincare",
  },
  {
    id: 9,
    img: "/Products/skincare/skincare4.png",
    price: 1199,
    DiscountPrice: 999,
    info: "Vitamin C Serum",
    category: "Skincare",
  },
  {
    id: 10,
    img: "/Products/Fastion/fastion1.png",
    price: 1199,
    DiscountPrice: 999,
    info: "Silk Scarf",
    category: "Fashion & Food",
  },
  {
    id: 11,
    img: "/Products/Fastion/fastion2.png",
    price: 1199,
    DiscountPrice: 999,
    info: "Silk Scarf",
    category: "Fashion & Food",
  },
  {
    id: 12,
    img: "/Products/Fastion/fastion3.png",
    price: 1199,
    DiscountPrice: 999,
    info: "Silk Scarf",
    category: "Fashion & Food",
  },
  {
    id: 13,
    img: "/Products/Fastion/fastion4.png",
    price: 1199,
    DiscountPrice: 999,
    info: "Silk Scarf",
    category: "Fashion & Food",
  },
  {
    id: 14,
    img: "/Products/Fastion/fastion5.png",
    price: 1199,
    DiscountPrice: 999,
    info: "Silk Scarf",
    category: "Fashion & Food",
  },
  {
    id: 15,
    img: "/Products/duo/Duo1.png",
    price: 1199,
    DiscountPrice: 999,
    info: "Silk Scarf",
    category: "Lips Duo",
  },
  {
    id: 16,
    img: "/Products/duo/Duo2.png",
    price: 1199,
    DiscountPrice: 999,
    info: "Silk Scarf",
    category: "Lips Duo",
  },
  {
    id: 17,
    img: "/Products/duo/Duo3.png",
    price: 1199,
    DiscountPrice: 999,
    info: "Silk Scarf",
    category: "Lips Duo",
  },
  {
    id: 18,
    img: "/Products/duo/Duo4.png",
    price: 1199,
    DiscountPrice: 999,
    info: "Silk Scarf",
    category: "Lips Duo",
  },
  {
    id: 19,
    img: "/Products/duo/Duo5.png",
    price: 1199,
    DiscountPrice: 999,
    info: "Silk Scarf",
    category: "Lips Duo",
  },
  {
    id: 20,
    img: "/Products/duo/Duo6.png",
    price: 1199,
    DiscountPrice: 999,
    info: "Silk Scarf",
    category: "Lips Duo",
  },
];

export default ShopProducts;
